# Generated by Django 5.1.3 on 2024-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_title_description_en_title_description_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, unique=True)),
                ('title_name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('title_name_tr', models.CharField(max_length=100, null=True, unique=True)),
                ('title_name_ky', models.CharField(max_length=100, null=True, unique=True)),
                ('title_name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('completed', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
